export const vaultKeys = {
  all: () => ["vault"],
  create: () => [...vaultKeys.all(), "create"],
  getMyVaults: () => [...vaultKeys.all(), "my-vaults"],
  getPublicVaults: () => [...vaultKeys.all(), "public"],
  getFollowingVaults: () => [...vaultKeys.all(), "following"],
  getNearbyVaults: (
    lat: number,
    lng: number,
    radius?: number,
    page?: number,
  ) => [...vaultKeys.all(), "nearby", lat, lng, radius ?? 50, page ?? 1],
  togglePin: () => [...vaultKeys.all(), "toggle-pin"],
  incrementView: () => [...vaultKeys.all(), "increment-view"],
  deleteVault: () => [...vaultKeys.all(), "delete"],
  getVaultDetails: (id: string) => [...vaultKeys.all(), "detail", id],
  updateVault: (id: string) => [...vaultKeys.all(), "update", id],
  publishVault: (id: string) => [...vaultKeys.all(), "publish", id],
  likeVault: (id: string) => [...vaultKeys.all(), "like", id],
  unlikeVault: (id: string) => [...vaultKeys.all(), "unlike", id],
  getComments: (vaultId: string) => [...vaultKeys.all(), "comments", vaultId],
  postComment: (vaultId: string) => [
    ...vaultKeys.all(),
    "comments",
    vaultId,
    "post",
  ],
  deleteComment: (vaultId: string) => [
    ...vaultKeys.all(),
    "comments",
    vaultId,
    "delete",
  ],
  getSavedVaults: () => [...vaultKeys.all(), "saved"],
  saveVault: (id: string) => [...vaultKeys.all(), "save", id],
  unsaveVault: (id: string) => [...vaultKeys.all(), "unsave", id],
  getVaultsByPlace: (
    placeName: string,
    placeLocation: string,
    page: number,
  ) => [...vaultKeys.all(), "by-place", placeName, placeLocation, page],
};
