export const authKeys = {
  all: () => ["authKeys"],
  login: () => [...authKeys.all(), "login"],
  signUp: () => [...authKeys.all(), "signUp"],
  forgotPassword: () => [...authKeys.all(), "forgotPassword"],
  resetPassword: () => [...authKeys.all(), "resetPassword"],
  changePassword: () => [...authKeys.all(), "changePassword"],
  twoFaStatus: () => [...authKeys.all(), "twoFaStatus"],
  twoFaSetup: () => [...authKeys.all(), "twoFaSetup"],
  twoFaVerify: () => [...authKeys.all(), "twoFaVerify"],
  twoFaDisable: () => [...authKeys.all(), "twoFaDisable"],
  twoFaLoginVerify: () => [...authKeys.all(), "twoFaLoginVerify"],
  linkedEmail: () => [...authKeys.all(), "linkedEmail"],
  changeEmailInitiate: () => [...authKeys.all(), "changeEmailInitiate"],
  changeEmailConfirm: () => [...authKeys.all(), "changeEmailConfirm"],
  sessions: () => [...authKeys.all(), "sessions"],
  loginActivity: () => [...authKeys.all(), "loginActivity"],
};
